example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5433/eagle_eye_local"
spring.datasource.username: "postgres"
spring.datasource.password: "postgres"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"

rest.security.issuer-uri: http://localhost:38080/auth/realms/dev

security.oauth2.client.client-id: organization-service
security.oauth2.client.client-secret: 2efa31b6-e3b9-4a7b-bea8-8059119a6a83
security.oauth2.client.user-authorization-uri: ${rest.security.issuer-uri}/protocol/openid-connect/auth
security.oauth2.client.access-token-uri: ${rest.security.issuer-uri}/protocol/openid-connect/token
security.oauth2.client.scope: openid
security.oauth2.client.grant-type: client_credentials

keycloak:
  # turn off keycloak spring boot auto-configuration:
  # We only want to use Spring Security without servlet container specific infrastructure
  # This allows us to pull the Keycloak configuration from here instead of keycloak.json
  enabled: false

  realm: dev
  auth-server-url: http://localhost:38080/auth
  # The client_id
  resource: licensing-service
  credentials:
    # The client_secret
    secret: 7e065f53-b655-435f-857d-85c616c450f8
  #ssl-required: external
  bearer-only: true
  # Configures what principal.getName() will return
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  token-minimum-time-to-live: 30